from __future__ import annotations

from rememb.helpers import MemoryStore, _store_context

from rememb.store._common import _generate_handoff, parse_handoff_restore_context
from rememb.store.crud import (
    clear_entries,
    consolidate_entries,
    delete_entries,
    delete_entry,
    diff_entry_versions,
    edit_entries,
    edit_entry,
    format_entries,
    get_config,
    get_stats,
    init,
    list_entry_versions,
    read_entries,
    read_entries_page,
    restore_deleted_entry,
    restore_entry_version,
    search_entries,
    update_config,
    write_entries,
    write_entry,
)
from rememb.store.handoffs import (
    build_handoff_package,
    close_session_with_handoff,
    read_structured_handoff,
    write_structured_handoff,
)
from rememb.store.review import (
    build_workstream_switch_package,
    compare_sessions,
    compare_workstreams,
    get_review_session,
    get_review_workstream,
    list_review_queue,
    list_workstream_queue,
    update_review_status,
)
from rememb.store.workstreams import (
    close_session,
    get_workstream_state,
    list_workstreams,
    open_workstream,
    resume_workstream,
    start_session,
    update_workstream_state,
)

__all__ = [
    "init",
    "get_config",
    "update_config",
    "list_workstreams",
    "open_workstream",
    "get_workstream_state",
    "parse_handoff_restore_context",
    "read_structured_handoff",
    "resume_workstream",
    "build_handoff_package",
    "get_review_session",
    "get_review_workstream",
    "list_workstream_queue",
    "compare_sessions",
    "compare_workstreams",
    "start_session",
    "close_session",
    "close_session_with_handoff",
    "update_workstream_state",
    "list_review_queue",
    "update_review_status",
    "write_structured_handoff",
    "write_entry",
    "write_entries",
    "consolidate_entries",
    "read_entries",
    "read_entries_page",
    "search_entries",
    "delete_entry",
    "delete_entries",
    "list_entry_versions",
    "restore_entry_version",
    "diff_entry_versions",
    "restore_deleted_entry",
    "edit_entry",
    "edit_entries",
    "clear_entries",
    "format_entries",
    "get_stats",
    "build_workstream_switch_package",
]

_store_instance = type('StoreModule', (), {
    'get_config': get_config,
    'update_config': update_config,
    'write_entry': write_entry,
    'write_entries': write_entries,
    'consolidate_entries': consolidate_entries,
    'read_entries': read_entries,
    'read_entries_page': read_entries_page,
    'search_entries': search_entries,
    'delete_entry': delete_entry,
    'delete_entries': delete_entries,
    'edit_entry': edit_entry,
    'edit_entries': edit_entries,
    'clear_entries': clear_entries,
})()
assert isinstance(_store_instance, MemoryStore), "store.py must implement MemoryStore Protocol"
